aws_region             = "us-east-1"
bucket_name            = "my-new-bucket-np2710"
bucket_owner           = "admin"
aws_account_id         = "588436839216"
iam_user               = "admin"
logging_target_bucket  = "logs-bucket-np2710"
bucket_environment     = "Dev"
